[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Mota_cpp"
authors = [{name = "Jason Leon", email = "jasonleon01@outlook.com"}]
dynamic = ["version", "description"]
